# Generated by Django 4.2.2 on 2023-07-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('starting_bid', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('FS', 'Fashion'), ('TY', 'Toys'), ('EL', 'Electronics'), ('HO', 'Home'), ('SP', 'Sports'), ('OT', 'Other')], max_length=2)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
