# Generated by Django 4.2.2 on 2023-07-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category_alter_listing_owner_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_winning_bid',
        ),
    ]
