# Generated by Django 4.2.2 on 2023-07-11 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
